### ISSUE TITLE
Linear Gradient Backgrounds from RGB Colors Broken

### ISSUE THREAD

**Issue by darth-cheney** [pharo-graphics/Bloc#13]
There is currently a bug with `BlLinearGradientPaint` whereby any stop color generated from `Color fromRgbTriplet:` will break the whole gradient.
  
Here is a working example you can test in a playground:
```smalltalk
| space el startColor endColor gradient|
space := BlSpace new.
space
	extent: 100@100;
	show.

"Set up the Gradient"
startColor := Color white.
endColor := (Color fromRgbTriplet: #(1 1 1)).
gradient := BlLinearGradientPaint new.
gradient
	start: 0@0;
	end: 50@50;
	stops: { 0.0 -> startColor. 1.0 -> endColor }.


"Create the inner element (with gradient background)"
el := BlElement new.
el
	size: 50@50;
	position: 25@25;
	background: gradient;
	border: (BlBorder paint: (Color black) width: 1).
	
"Add to space"
space root addChild: el.
```
  
If you see what I see, the example above will simply have a plain white background and no gradient at all.
  
Note that if you switch `endColor` to be `Color black` it will work just fine, as it will with any declared color from the `Color` class, like `Color gray lighter lighter` etc.

**Comment by syrel** [comment]
Could you explain what gradient you expect? Because from what I see you declare no gradient :)

The reason is that `(Color fromRgbTriplet: #(1 1 1)) = Color white "true"`
`Color fromRgbTriplet: #(1 1 1)` creates a color with red set to 1.0, green set to 1.0, blue set to 1.0 and alpha set to 1.0 which is exactly white color. And of course you get plain background.

However, if you would change `Color fromRgbTriplet: #(1 1 1)` to `Color fromRgbTriplet: #(1 0 0)`
you would see a linear gradient from white to red, since  `Color fromRgbTriplet: #(1 0 0)` creates a color with red set to 1.0, green set to 0.0 and blue set to 0.0.

It works :)

**Comment by GlennCavarle** [comment]
That's what I was going to say :)

**Comment by darth-cheney** [comment]
Hi @GlennCavarle @syrel -- You guys are correct: I have not created much of a gradient. But isn't the Pharo `Color` implementation of RGB reversed? Zero values are supposed to indicate the darkest possible color, while full values (255) should be the lightest.
  
Am I crazy (or lacking enough coffee)? Shouldn't `255 255 255` be white and `0 0 0` be black?

**Comment by syrel** [comment]
RGB has multiple numeric representation notations (https://en.wikipedia.org/wiki/RGB_color_model#Numeric_representations)
Pharo uses Arithmetic notation where channels take values within an interval [0...1].

However, it is possible to create a Color with different arithmetic notation by specifying a `range`:

```
Color r: 255 g: 255 b: 255 range: 255
```

**Comment by darth-cheney** [comment]
Ah yes, I see now. I have been poisoned by years of CSS. Thanks
