### ISSUE TITLE
[Layouts] BlTextElement text vanishes on parent bloc resize

### ISSUE THREAD

**Issue by darth-cheney** [pharo-graphics/Bloc#17]
Again, not sure if I'm screwing something up or if it's a bug, but when I have a `BlTextElement` that is a child of either a Grid or Frame layout, the text will vanish upon resizing.
  
To see an example of what I mean, go ahead and clone [my tests repository](https://github.com/darth-cheney/bloc-tests) and run `CopWindow exampleBasic`. Double-click the titlebar to get the halo and then try resizing.
  
Here are screenshots for reference:
![screen shot 2017-04-01 at 3 00 39 pm](https://cloud.githubusercontent.com/assets/1640299/24581573/0f6eb7fc-16ec-11e7-9c60-102d9d964346.png)
![screen shot 2017-04-01 at 3 00 52 pm](https://cloud.githubusercontent.com/assets/1640299/24581572/0f6dae16-16ec-11e7-9df1-2754f918645b.png)
![screen shot 2017-04-01 at 3 01 03 pm](https://cloud.githubusercontent.com/assets/1640299/24581571/0f6d432c-16ec-11e7-8c88-361b91af478a.png)
  
Related question: Is there a way to open up an expansive `BlSpace` in an OSWindow or something, so that I can experiment as if Bloc is the true graphics system?

Thanks as always.

**Comment by syrel** [comment]
Hi Eric,

Text part is under active development :) Yes, it is a known problem and I will fix it at some point, but for now you have to live with it, sorry.

> Is there a way to open up an expansive BlSpace in an OSWindow or something, so that I can experiment as if Bloc is the true graphics system?

Unfortunately, because of changes in how Pharo 6 main window works there is no way to open bloc in OSWindow. Simply because OSWindow does not work yet as expected :) Funny is that Bloc was designed and always worked in OSWindow and around month ago we had to port it back to morphic 😢 
We have to wait official Pharo 6 release and then see what is the status and if it will not work we will have to find a workaround...

**Comment by girba** [comment]
This should work now.
