### ISSUE TITLE
BlElement buffer-able

### ISSUE THREAD

**Issue by ELePors** [pharo-graphics/Bloc#267]
It could be very usefull to have an inner property of BlElement to be able to bufferize it, or a Trait which enable a BlElement to do so...
When you draw a complex BlElement with multiple BlElement transformed as children, and when children are not updating all the time... the developper should be able so specify a "buffered" BlElement to render only the buffer (when not dirty) and not recompute all child when just moving it.

**Comment by labordep** [comment]
This is particularly used when some complexe BlElements composition are used to decorate an UI as non-interactive elements. For example you can imagine a background generated with BlElement (for example depending screen size) as a mosaic of advanced image : 

![image](https://github.com/pharo-graphics/Bloc/assets/49183340/b7a7baee-9aff-4cd0-820f-3e8ef8567c3c)

![image](https://github.com/pharo-graphics/Bloc/assets/49183340/35423ec2-6052-4b50-82c3-d91b58e427cd)

**Comment by ELePors** [comment]
Yes and it will be costless to move a texture drawn by the BlElement than drawing each time each child...

**Comment by tinchodias** [comment]
There is beInSingleCompositionLayer that flags a BlElement as buffered. I did an experiment with the SDL_Texture, but also would improve with a cache at the level of Cairo. e.g. do cache the cairo_surface_t or group instead of redrawing as now.

**Comment by ELePors** [comment]
Yes it is a good idea, and more : if dirty, the BlElement must have to refresh the buffer (or a mechanism that allows it)... it is not the idea to have a non updatable BlElement... 
But yes, for me it is very important to do beautiful and reactive UI things.

**Comment by tinchodias** [comment]
Hi, this is a proposal for this request: https://github.com/pharo-graphics/Bloc/pull/268

**Comment by tinchodias** [comment]
This is fixed by #268

Basically, when an element has to draw itself on a canvas and responds true to `wantsSeparateCompositingLayer`, then it's drawn in a new Cairo surface, and then "painted" into the host space canvas. Next pulse with drawing phase needed, if the element wasn't invalidated, the Cairo surface will be painted again into the host space canvas without need to redraw again.

It's quite basic for the moment: if a `BlElement` answers true to `wantsCompositionLayer`, then it will be on a separate Cairo surfaces.

There are two strategies for doing it:
- `anElement beInSingleCompositionLayer`, that caches itself and all recursive children in a single surface (it doesn't matter if any of the children have one of these options)
- `anElement beInSeparateCompositionLayer`, that is similar to previous option but any children can be cached separately.

Note: Element effect's have `wantsCompositionLayer` on their API, which the element queries to decide if it has a composition layer. For example, `BlGaussianShadowEffect` answers true.
