### ISSUE TITLE
addEventHandlerOn:do: does return the element, not the handler. Should it?

### ISSUE THREAD

**Issue by StephanEggermont** [pharo-graphics/Bloc#31]
handler := drag addEventHandlerOn: BlDragEvent do: [ :evt |
	evt consumed: true.
	drag position: evt position].
drag addEventHandlerOn: BlDragEndEvent do: [ :evt |
	drag removeEventHandler: handler. 
	evt consumed: true].

**Comment by syrel** [comment]
It is intentional that all setters in `BlElement` always return `self`. This way there is no need to double check if there is a need to send `yourself` in the case of cascaded message sends and we have high level of consistency. It turned out that `addEventHandlerOn:` should be used more or less only in case of fast experiments in Playground. For the real world application I highly suggest to subclass `BlElementEventListener` and override `dragEndEvent: anEvent`. So the example above would look like:

```smalltalk
listener := MyDraggingEventListener new.
drag addEventHandler: listener.
drag removeEventHandler: listener.
```
and dragging methods:

```smalltalk
dragEvent: anEvent
   anEvent consumed: true.
   "`anEvent currentTarget` is an element to which event listener is added"
   anEvent currentTarget position: anEvent position
```

```smalltalk
dragEndEvent: anEvent
   anEvent consumed: true.
   anEvent currentTarget removeEventHandler: self
```

Advantages:
- clean code
- support coding in debugger
- no block closures
- reduces possibility of memory leaks
- just one event listener for all related events


If you still wish to use `addEventHandlerOn:do:` and preserve reference to the event handler you can create it explicitly:

```smalltalk
handler := BlEventHandler on: BlDragEndEvent do: [:evt| "..." ].
drag addEventHandler: handler.
```

**Comment by StephanEggermont** [comment]
Ah, an interesting design decision. That does not seem to be enforced in GToolkit-Mondrian

**Comment by StephanEggermont** [comment]
Ah yes. A further advantage of using the `MyDraggingEventListener` is that it is a good place to store the starting offset when starting to drag
