### ISSUE TITLE
Easily get size of a BlElement

### ISSUE THREAD

**Issue by Eliott-Guevel** [pharo-graphics/Bloc#533]
As of now, there's no easy way to get the **size** property of a `BlElement`.

A simple example such as
```smalltalk
e := BlTextElement new
	size: 50 asPoint; 
	yourself.
	
self inform: e size
```
returns this error
![size error](https://github.com/pharo-graphics/Bloc/assets/76944457/4c5174e3-5bc4-4a91-8ab3-e08b9b7550ad)
which returns `0 @ 0` and not  `50 @ 50`

**Comment by plantec** [comment]
two points:
first the exception is because #inform: takes a string as argument.
the following script will run without error;
```
e := BlTextElement new
	size: 50 asPoint; 
	yourself.
self inform: e size asString
```
second point, you will see 0@0 instead of the expected 50@50.
This is normal.

to get the requested size you can do as follow:
```
e := BlTextElement new
	size: 50 asPoint; 
	yourself.
requestedSize := (e constraints horizontal resizer size) @ (e constraints vertical resizer size).
self inform: requestedSize asString
```
When you send #size: to an element, consider it as a request. This request is not interpreted immediately.
Instead it is evaluated by the layout that is run during a layout phase.
Have a look at BlSpaceFrame and BlSpaceFramePhase.

```
e := BlTextElement new
	size: 50 asPoint; 
	yourself.
e whenLayoutedDoOnce: [ self inform: e size asString ].
e openInSpace
```
Notice that using  whenLayoutedDoOnce:  seems cool but it is not a good practice.

**Comment by tinchodias** [comment]
Hello @Eliott-Guevel I agree with the reply of Alain. Is the last snippet, with `whenLayoutedDoOnce:`, convenient enough for your use case?

**Comment by Eliott-Guevel** [comment]
It would do, just need to be referenced in an example (since it's only called by 2 methods in Bloc and Toplo at the moment which are not that explicit concerning its use). 
The `whenLayoutedDoOnce:` method could also use a small comment detailing this use case as well as other useful ones (if any other exists). 
Thanks in advance

**Comment by plantec** [comment]
second try then:
The actual size of an element is computed by the layout.
Thus, if one need to get the size of an element one have to be sure that its layout applied.
This is the purpose of #whenLayoutedDoOne: (when layout applied do once) which intention is to run the block passed as argument only one time just after the layout applied.

**Comment by plantec** [comment]
I added it in the comment

**Comment by tinchodias** [comment]
I also added a related comment about this at the end of this [getting started page](https://github.com/pharo-graphics/Bloc/blob/dev/doc/1-GettingStarted.md#how-bloc-works). To be improved, but it's something. The base is a text of @Nyan11 that I copied from Toplo repo.
