### ISSUE TITLE
crash on Pharo12 if children message sent to BlSpace

### ISSUE THREAD

**Issue by lucretiomsp** [pharo-graphics/Bloc#615]
if I send by mistake the message children to a BlSpace instead of sending it to its root, Pharo crashes

**Comment by tinchodias** [comment]
Hello @lucretiomsp what do you mean by crash? I executed this:
```
s := BlSpace new.
s show.
s children.
```
and obtained a debugger because the BlSpace class and superclasses don't define `children` selector:
<img width="633" alt="Screenshot 2024-10-14 at 19 04 32" src="https://github.com/user-attachments/assets/68d34690-3788-4b27-9a19-7ca1b6591569">

**Comment by tinchodias** [comment]
@lucretiomsp please reopen if needed

**Comment by lucretiomsp** [comment]
@tinchodias no problems with a fresh image, so maybe something related with my Image
