### ISSUE TITLE
Improve performance for BlGaussianShadowEffect

### ISSUE THREAD

**Issue by ElvinPero** [pharo-graphics/Bloc#645]
Current implementation of BlGaussianShadow effect is slow and becomes slower when multiple elements are rendered with shadows.  

To do:  Improve Perfomance of BlGaussianShadowEffect (as a separate named effect ).

**Comment by tinchodias** [comment]
It's quite done for circle and rectangle, but trying to make it work on rounded rectangle today

**Comment by tinchodias** [comment]
@ElvinPero Please try Tp33 with current Bloc:master
It is still slow in first frame, when showing the space, but then it works quite smooth due to shadows are cached if no change in element extent.
No need to change anything in Tp33 as it is the same class, same everything except implementation of BlGaussianShadowEffect.

This is while I achieve to PR the gradient shadow, that is fast also in first rendering so space will show fast.

**Comment by tinchodias** [comment]
Good! well, we can close this issue for now.
