### ISSUE TITLE
Super in traits does not work in latest blockclosure

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Bloc#73]
While it work in bytecode v3, using super in traits does not work the latest bytecode in Pharo 90

**Comment by seandenigris** [comment]
What is the status of this? It seems to work in P9 (Ubuntu), but there are no commits referencing this issue and there's this on Discord from @MarcusDenker:
> It was working "by accident". It was broken due to full blocks...  Does super for traits make sense? I guess not. We need to discuss/think what the best is after, but for Pharo9 the easiest was to fix the regression in compared to Pharo8

@syrel wrote:
> In my opinion, super in traits should not work. It is a good decision to ban it. I was reporting a vm crash when that happens... Traits replace inheritance and transform design from is-a relationship to has-a , which is very powerful. And when it comes to has-a - the super does not really make sense, since inheritance is not defined here

And I wrote:
> While I see your point in principle, as a practical matter I disagree because it takes away power that is useful. For example, in this issue I had to jump through hoops to overcome the inability http://forum.world.st/Trait-Change-in-Pharo-9-td5119000.html

It seems to me that trusting users and not limiting their power is a fundamental principle behind Smalltalk. Is there some compelling danger here I'm missing?

The thing is that not being able to send messages to the client's superclass leads to convoluted code to workaround e.g. trait calls otherwise-unnecessary helper just to reach superclass.
