### ISSUE TITLE
GtTranscript not found error on startup

### ISSUE THREAD

**Issue by tinchodias** [pharo-graphics/Bloc#80]
After I load in P8 following isntructions in README and save&quit, I get this error next time I try to open the image:

~~~
NotFound: #GtTranscript not found in SystemDictionary
[ NotFound signalFor: self in: anEnvironment ] in ByteSymbol(String)>>asClassInEnvironment: in Block: [ NotFound signalFor: self in: anEnvironment ]
SystemDictionary(Dictionary)>>at:ifPresent:ifAbsent:
ByteSymbol(String)>>asClassInEnvironment:ifAbsent:
ByteSymbol(String)>>asClassInEnvironment:
ByteSymbol(String)>>asClass
BlBlocUIManager>>activate
UIManager class>>default:
BlBlocUIManager class>>startup:
~~~

**Comment by tinchodias** [comment]
In a recent GT image, it's defined as:
```

Object subclass: #GtTranscript
	instanceVariableNames: 'mutex text announcer'
	classVariableNames: ''
	package: 'GToolkit-Transcript'
```

**Comment by tinchodias** [comment]
I tried removing the execution of this parrt of the code, but the image anyway gets unresponsive... only that silently. No error log of PharoDebug.log. Should look again.

**Comment by tinchodias** [comment]
UPDATE:

The unresponsive image happens only when using:

~~~
curl https://get.pharo.org/64/80+vmHeadlessLatest | bash
~~~

but not with

~~~
curl https://get.pharo.org/64/80+vm | bash
~~~

So, I pushed 52cacd88f43db88985652e4962870465f8f2a6af that removes the `activate` method (the difference with super implementation was installing the GtTranscript which is undeclared).

**Comment by Ducasse** [comment]
Excellent!

**Comment by tinchodias** [comment]
Hi @syrel 
Any opinion on the reference to `GtTranscript`? 
I removed the `BlBlocUIManager>>activate` method in 52cacd8, at least for the moment.

**Comment by syrel** [comment]
Great decision! Thank you for noticing the reference to GtTranscript from Bloc, it should not be there.

At some point the `activate` method (maybe a bit modified) should be brought back. Otherwise the UI manager is always the default MorphicUIManager which is only useful when morphic bloc host is used.
Morphic Bloc Host is implemented in such a way that Bloc runs within Morphic UI Process which is nice as a fallback behavior. However, what we really want is to be able to run Bloc in its own independent UI Process. Unfortunately, the debugging and UI manager infrastructure in Pharo is not made to support multiple UI processes, that is why we had to implement our own extremely hacking UI manager that tries to handle multiple UI processes.

Let me know if you would like to know more about challenges related to debugging UI frameworks.
