### ISSUE TITLE
Bloc depends on feenk beacon 

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Bloc#93]
Because 

BlMarkElementNeedsPaintSignal is a subclass of 

```
ThisContextSignal subclass: #ContextStackSignal
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Beacon-ExtraSignals'
```

```
BeaconSignal subclass: #ThisContextSignal
	instanceVariableNames: 'stack'
	classVariableNames: ''
	package: 'Beacon-ExtraSignals'
```

I do not get why Paint related signal would need a stack.

**Comment by syrel** [comment]
Hi
This signal helps to understand who and from where sends the repaint requests. Without stack it makes no sense

**Comment by Ducasse** [comment]
Ok I will clone beacon-bloc. 
But reifying the stack all the time is super costly. 
It feels like a debugging always one. 
thisContext as real consequences on JIT because it reifies the contexts.

**Comment by Ducasse** [comment]
This is strange in Bloc I do not have any references to BlMarkElementNeedsPaintSignal

**Comment by syrel** [comment]
@girba introduced an improvement to the announcer framework that was integrated in Pharo that allows announcements to prepareForDelivery. It means that if there are no subscribers the stack will not be reified which makes signaling of the stack signal very cheap. Stack signals are one of the very few meaningful ways to debug complex internals of UI frameworks. Debugger does not not work in this case because it spawns a new UI process that modifies the state that we are trying to debug

**Comment by Ducasse** [comment]
Ok thanks for the explanation.

**Comment by tinchodias** [comment]
Sounds useful but I can't locate the class (in dev-1.0 nor in the history of the repo). So let's close the issue.
