### ISSUE TITLE
Yet another hidden dependency from Bloc to GToolkit.

### ISSUE THREAD

**Issue by Ducasse** [pharo-graphics/Bloc#98]
BlGridLayoutExamples packaged in Bloc-Layout-Examples-Grid
depends in fact of TGtExampleAssertable

```
TGtExampleAssertable users
>>> an IdentitySet(GtExampleProvider GtAbstractDummyExamples GtDummyExamplesInPackage1Root BlGridLayoutExamples)
```

Super bingo 
```
Object subclass: #BlGridLayoutExamples
	uses: TBlLayoutExamplesSetup + TGtExampleAssertable
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Bloc-Layout-Examples-Grid'
```

Obviously some tools are not correct in GToolkit because this is clearly a dependency from Bloc to GToolkit!

**Comment by Ducasse** [comment]
Fixed.
I just removed TGtExampleAssertable from the definition of BlGridLayoutExamples!!!
And I will migrate it to SUnit.

**Comment by syrel** [comment]
Somebody introduced this dependency by accident and human mistake. It does not mean the tools are bad @girba

**Comment by girba** [comment]
`TGtExampleAssertable` is in the examples engine which is a standalone engine and is part of the dependencies of Bloc.

<img width="912" alt="Screen Shot 2021-02-14 at 9 46 11 PM" src="https://user-images.githubusercontent.com/249595/107888663-13f54b00-6f0e-11eb-8bc7-b824d38f1c06.png">

I am not sure what you want to migrate to SUnit.

**Comment by Ducasse** [comment]
Simple super easy super simple I want Bloc without any dependency to GToolkit. 
And Bloc-Examples in the Bloc project SHOULD NOT depend on GTExample.
To me there was an arrow from Bloc to GTExampleEngine and it cannot be.
I could not load Bloc with it. So now this is fixed.

**Comment by Ducasse** [comment]
I'm converting all the Bloc-Examples to SUnit tests and I'm discovering hidden dependency. 
I have a build now in P8 and now I want a green bar. 
And I'm getting there. 
Executed 277 Tests with 7 Failures and 1 Errors in 2.83s.

**Comment by Ducasse** [comment]
I close the issue since it is fixed. This is funny that only one Example needs to use TGtExampleAssertable. 
I could not get why but since I removed it. I will focus on the next problem.

**Comment by girba** [comment]
Maybe I was not clear. This is an explicit dependency in BaselineOfBloc and we are testing that dependency. I understand it's a dependency that you do not like, but this is not a hidden dependency. I was merely pointing out that the tools work as intended.

Just because it is named GToolkit Examples Engine, it's still a standalone engine with no external dependencies.

**Comment by Ducasse** [comment]
Ok,
just a question about your graph. Why you do not have a bloc -> GTExampleEngine?

**Comment by girba** [comment]
Because Metacello is very slow. It looks like one source of slowness is when it tries to load the same baseline twice. So, we limited the amounts of dependencies for now and rely on the indirect dependencies.

We are actually building another loader that works with the same specifications to make it faster. It's not ready yet though.

**Comment by Ducasse** [comment]
Ahhh I will check the log of the build because indeed I had the impression that everything was loading twice but I thought it was me that could not understand it.
